trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'AzureConnection'
    appName: 'my-java-app'
    package: 'target/*.jar'